# Generated by Django 4.2.3 on 2023-08-02 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_alter_category_options_item'),
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConversationMessageForm',
            new_name='ConversationMessageModel',
        ),
        migrations.RenameModel(
            old_name='Conversation',
            new_name='ConversationModel',
        ),
    ]
